AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster, Task Definition, and Service for Backend with DB Environment Variables

Parameters:
  Environment:
    Type: String
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  BackendSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  TargetGroupArn:
    Type: String
  ClusterName:
    Type: String
    Default: backend-cluster
  ContainerName:
    Type: String
    Default: backend-app
  ImageUrl:
    Type: String
  # DBName:
  #   Type: String
  # DBUser:
  #   Type: String
  # DBPass:
  #   Type: String
  #   NoEcho: true
  # DBHost:
  #   Type: String

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Environment}-ecsTaskExecutionRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: AllowCloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${Environment}-backend-task"
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ImageUrl
          PortMappings:
            - ContainerPort: 3000
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: ecs-logs
              awslogs-region: us-east-1
              awslogs-stream-prefix: ecs
          # Environment:
          #   - Name: DB_NAME
          #     Value: !Ref DBName
          #   - Name: DB_USER
          #     Value: !Ref DBUser
          #   - Name: DB_PASS
          #     Value: !Ref DBPass
          #   - Name: DB_HOST
          #     Value: !Ref DBHost
          Essential: true

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: TaskDefinition
    Properties:
      ServiceName: !Sub "${Environment}-backend-service"
      Cluster: !Ref ECSCluster
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !Ref BackendSecurityGroupId
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroupArn

Outputs:
  ECSClusterName:
    Value: !Ref ECSCluster
  TaskDefinitionArn:
    Value: !Ref TaskDefinition
  ECSServiceName:
    Value: !Ref ECSService