AWSTemplateFormatVersion: '2010-09-09'
Description: RDS MySQL Instance in Private Subnets

Parameters:
  DBName:
    Type: String
    Default: povomah
    Description: The database name

  DBUser:
    Type: String
    Default: admin
    Description: Master username

  DBPassword:
    Type: String
    NoEcho: true
    Default: roche938435
    Description: Master user password

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: First private subnet

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Second private subnet

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group that allows backend access

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnets for RDS DB
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: RDS-SubnetGroup

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: mysql
      EngineVersion: 8.0
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      StorageType: gp2
      DBName: !Ref DBName
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      MultiAZ: false
      BackupRetentionPeriod: 0
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: RDSInstance

Outputs:
  DBEndpoint:
    Description: The endpoint address of the RDS instance
    Value: !GetAtt MyDBInstance.Endpoint.Address
    Export:
      Name: RDS-Endpoint

  DBName:
    Value: !Ref DBName
    Export:
      Name: RDS-DBName

  DBUser:
    Value: !Ref DBUser
    Export:
      Name: RDS-User
